// This file was auto-generated by ML.NET Model Builder. 

using System;
using System.IO;
using System.Linq;
using Microsoft.ML;
using HandwritingRecognitionML.Model;

namespace HandwritingRecognitionML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            ModelBuilder.CreateModel();

            Console.WriteLine("=============== End of process ===============");
        }
    }
}
