// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace TaxiFareML.Model
{
    public class TaxiFareModelOutput
    {
        [ColumnName("Score")]
        public float FareAmount { get; set; }
    }
}
