version: '3'
services:
  nginx:
    image: nginx:alpine
    hostname: 'nginx'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf:ro
      - ./nginx/ssl/localhost.crt:/etc/ssl/certs/localhost.crt:ro
      - ./nginx/ssl/localhost.key:/etc/ssl/certs/localhost.key:ro
      - ./nginx/logs/:/var/log/nginx/
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - api
    restart: always

  api:
    build: ./src
    ports:
      - '5000'
    restart: always
